package youyihj.zenutils.impl.mixin.vanilla;

import com.llamalad7.mixinextras.injector.wrapoperation.Operation;
import com.llamalad7.mixinextras.injector.wrapoperation.WrapOperation;
import com.llamalad7.mixinextras.sugar.Share;
import com.llamalad7.mixinextras.sugar.ref.LocalRef;
import net.minecraftforge.fml.client.GuiModList;
import net.minecraftforge.fml.common.ModContainer;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.Shadow;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;
import youyihj.zenutils.impl.config.ConfigAnytimeAnytime;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

@Mixin(GuiModList.class)
public abstract class MixinGuiModList {
    @Shadow(remap = false) private ArrayList<ModContainer> mods;

    @WrapOperation(
            method = "reloadMods",
            at = @At(value = "INVOKE", target = "Ljava/util/ArrayList;clear()V"),
            remap = false
    )
    private void keepAutogeneratedMods(ArrayList<ModContainer> mods, Operation<Void> original, @Share("keptMods")LocalRef<List<ModContainer>> keptMods) {
        keptMods.set(
                mods.stream()
                .filter(mod -> mod.getMetadata() != null)
                .filter(mod -> mod.getMetadata().updateUrl.equals(ConfigAnytimeAnytime.DESCRIPTOR))
                .collect(Collectors.toList())
        );
        original.call(mods); //clear
    }

    @Inject(
            method = "reloadMods",
            at = @At("TAIL"),
            remap = false
    )
    private void keepAutogeneratedMods(CallbackInfo ci, @Share("keptMods")LocalRef<List<ModContainer>> keptMods){
        if(keptMods.get() != null)
            this.mods.addAll(keptMods.get()); //add at end of list
    }
}
