package youyihj.zenutils.impl.mixin.vanilla;

import com.llamalad7.mixinextras.injector.wrapoperation.Operation;
import com.llamalad7.mixinextras.injector.wrapoperation.WrapOperation;
import net.minecraftforge.fml.client.config.GuiConfig;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import youyihj.zenutils.impl.config.ConfigAnytimeAnytime;

@Mixin(GuiConfig.class)
public abstract class MixinGuiConfig {
    @WrapOperation(
            method = "actionPerformed",
            at = @At(value = "INVOKE", target = "Lnet/minecraftforge/fml/common/Loader;isModLoaded(Ljava/lang/String;)Z", remap = false)
    )
    private boolean keepAutogeneratedMods(String modId, Operation<Boolean> original) {
        boolean isLoaded = original.call(modId);
        return isLoaded || ConfigAnytimeAnytime.registeredGuiContainers.containsKey(modId);
    }
}
